// Icon constants for consistent usage
export const ICONS = {
  // File Types
  PHOTO: 'image',
  VIDEO: 'video',
  DOCUMENT: 'file',
  FOLDER: 'folder',
  ALL_FILES: 'folder-open',
  
  // Actions
  UPLOAD: 'cloud-upload-alt',
  DOWNLOAD: 'cloud-download-alt',
  SEARCH: 'search',
  FILTER: 'filter',
  MENU: 'bars',
  CLOSE: 'times',
  GRID: 'th',
  LIST: 'list',
  
  // Media Controls
  PLAY: 'play',
  PAUSE: 'pause',
  FORWARD: 'forward',
  BACKWARD: 'backward',
  VOLUME_ON: 'volume-up',
  VOLUME_OFF: 'volume-mute',
  FULLSCREEN: 'expand',
  EXIT_FULLSCREEN: 'compress',
  SETTINGS: 'cog',
  
  // Status
  CHECK: 'check-circle',
  ERROR: 'exclamation-circle',
  WARNING: 'exclamation-triangle',
  LOADING: 'sync',
  CONNECTED: 'link',
  DISCONNECTED: 'unlink',
  
  // User Interface
  HEART: 'heart',
  HEART_OUTLINE: ['far', 'heart'],
  SHARE: 'share',
  COPY: 'copy',
  TRASH: 'trash',
  EDIT: 'edit',
  LINK: 'external-link-alt',
  USER: 'user',
  EMAIL: 'envelope',
  LOCK: 'lock',
  EYE: 'eye',
  EYE_OFF: 'eye-slash',
  LOGOUT: 'sign-out-alt',
  KEY: 'key',
  ARROW_LEFT: 'arrow-left',
  ARROW_RIGHT: 'arrow-right',
  MORE_VERTICAL: 'ellipsis-v',
  CHEVRON_DOWN: 'chevron-down',
  CHEVRON_UP: 'chevron-up',
  PLUS: 'plus',
  REFRESH: 'redo',
  POWER: 'power-off',
  
  // Brands
  GOOGLE: ['fab', 'google'],
};

// Font Awesome icon library configuration
import { library } from '@fortawesome/fontawesome-svg-core';
import { 
  faCloudUploadAlt, 
  faCloudDownloadAlt,
  faSearch,
  faFilter,
  faBars,
  faTimes,
  faTh,
  faList,
  faImage,
  faVideo,
  faFile,
  faFolder,
  faFolderOpen,
  faPlay,
  faPause,
  faForward,
  faBackward,
  faVolumeUp,
  faVolumeMute,
  faExpand,
  faCompress,
  faCog,
  faCheckCircle,
  faExclamationCircle,
  faExclamationTriangle,
  faSync,
  faLink,
  faUnlink,
  faHeart,
  faShare,
  faCopy,
  faTrash,
  faEdit,
  faExternalLinkAlt,
  faUser,
  faEnvelope,
  faLock,
  faEye,
  faEyeSlash,
  faSignOutAlt,
  faKey,
  faArrowLeft,
  faArrowRight,
  faEllipsisV,
  faChevronDown,
  faChevronUp,
  faPlus,
  faRedo,
  faPowerOff,
} from '@fortawesome/free-solid-svg-icons';
import { faHeart as faHeartRegular } from '@fortawesome/free-regular-svg-icons';
import { faGoogle } from '@fortawesome/free-brands-svg-icons';

// Add all icons to library
library.add(
  faCloudUploadAlt, 
  faCloudDownloadAlt, 
  faSearch, 
  faFilter, 
  faBars, 
  faTimes,
  faTh, 
  faList, 
  faImage, 
  faVideo, 
  faFile, 
  faFolder, 
  faFolderOpen, 
  faPlay,
  faPause, 
  faForward, 
  faBackward, 
  faVolumeUp, 
  faVolumeMute, 
  faExpand, 
  faCompress,
  faCog, 
  faCheckCircle, 
  faExclamationCircle, 
  faExclamationTriangle, 
  faSync,
  faLink, 
  faUnlink, 
  faHeart, 
  faHeartRegular, 
  faShare, 
  faCopy, 
  faTrash, 
  faEdit,
  faExternalLinkAlt, 
  faUser, 
  faEnvelope, 
  faLock, 
  faEye, 
  faEyeSlash, 
  faSignOutAlt,
  faKey, 
  faArrowLeft, 
  faArrowRight, 
  faEllipsisV, 
  faChevronDown, 
  faChevronUp,
  faPlus, 
  faRedo, 
  faPowerOff,
  faGoogle
);

export default ICONS;